import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Glowlytics Privacy Policy. Learn how BDQ Holdings LLC handles your data.",
};

const sections: { num: string; title: string; body: React.ReactNode }[] = [
  {
    num: "01",
    title: "Information we collect",
    body: (
      <>
        <p>
          We collect the following types of information to provide and improve the Glowlytics
          experience:
        </p>
        <ul>
          <li>
            <strong>Account information</strong> — name, email address, and authentication
            credentials managed through Clerk.
          </li>
          <li>
            <strong>Skin scan photos</strong> — images captured via your device camera for skin
            analysis.
          </li>
          <li>
            <strong>Face data used for scan alignment</strong> — a face bounding box, approximate
            face size, head angle, and facial landmark / mesh coordinates processed on-device
            during live camera preview so scans are framed consistently. We do not use this data
            for face recognition or identity verification.
          </li>
          <li>
            <strong>Health metrics</strong> — skin scores, condition assessments, and trend data
            generated by our AI analysis.
          </li>
          <li>
            <strong>Product usage data</strong> — skincare products you log, including barcode
            scans and usage patterns.
          </li>
          <li>
            <strong>Demographic information</strong> — age, skin type, and related details you
            provide during onboarding.
          </li>
          <li>
            <strong>Device information</strong> — device type, operating system, and app version
            for compatibility and troubleshooting.
          </li>
        </ul>
      </>
    ),
  },
  {
    num: "02",
    title: "How we use your data",
    body: (
      <>
        <p>
          Your data is used exclusively to deliver and improve the Glowlytics service:
        </p>
        <ul>
          <li>
            <strong>Skin analysis</strong> — processing your scan photos through our fine-tuned
            AI model to identify conditions and generate scores.
          </li>
          <li>
            <strong>Face alignment</strong> — using live face-position and landmark data on your
            device to guide framing, distance, and angle before a scan is captured.
          </li>
          <li>
            <strong>Trend tracking</strong> — monitoring changes in your skin health over time to
            surface meaningful insights.
          </li>
          <li>
            <strong>Personalized recommendations</strong> — providing evidence-based guidance
            informed by AAD and ACOG clinical guidelines via our RAG pipeline.
          </li>
          <li>
            <strong>Service improvement</strong> — understanding aggregate usage patterns to
            improve app functionality and accuracy.
          </li>
        </ul>
        <p>
          <strong>We do not sell your data. We do not use your data for advertising.</strong>
        </p>
      </>
    ),
  },
  {
    num: "03",
    title: "Face data",
    body: (
      <>
        <p>
          When you open the guided camera, Glowlytics processes limited face data on-device so it
          can align your scan consistently. This face data may include a face bounding box,
          approximate face size, head angle, and facial landmark / mesh coordinates during live
          preview.
        </p>
        <ul>
          <li>
            <strong>Purpose</strong> — center your face, confirm distance, and keep scan framing
            consistent over time.
          </li>
          <li>
            <strong>Retention</strong> — live face-alignment data is discarded when the camera
            session ends and is not stored as a reusable biometric template.
          </li>
          <li>
            <strong>Sharing</strong> — live face-alignment data is not shared with third parties.
            Captured scan photos may be processed by our secure backend and OpenAI under our API
            agreement to generate non-diagnostic skin insights.
          </li>
          <li>
            <strong>What we do not do</strong> — Glowlytics does not use face data for identity
            verification, face recognition, emotion detection, advertising, or profiling.
          </li>
        </ul>
      </>
    ),
  },
  {
    num: "04",
    title: "Storage and security",
    body: (
      <>
        <p>Your data is stored using a combination of local and server-side storage:</p>
        <ul>
          <li>
            <strong>Local device storage</strong> — scan history, preferences, and cached data
            are stored on your device using AsyncStorage.
          </li>
          <li>
            <strong>Ephemeral face alignment data</strong> — live face bounding boxes and
            landmark / mesh coordinates stay on-device during camera preview and are discarded
            after the session ends.
          </li>
          <li>
            <strong>Encrypted backend</strong> — data synced to our servers is stored in
            PostgreSQL with TLS encryption in transit.
          </li>
        </ul>
        <p>
          We employ industry-standard security practices to protect your information, including
          encrypted connections, secure authentication via Clerk, and server-side API key
          management to prevent exposure of credentials.
        </p>
      </>
    ),
  },
  {
    num: "05",
    title: "Third-party services",
    body: (
      <>
        <p>Glowlytics integrates the following third-party services:</p>
        <ul>
          <li>
            <strong>Clerk</strong> — handles authentication, account management, and secure
            session tokens. Subject to{" "}
            <a href="https://clerk.com/privacy" target="_blank" rel="noopener">
              Clerk&apos;s Privacy Policy
            </a>
            .
          </li>
          <li>
            <strong>OpenAI</strong> — powers our vision-based skin analysis via their API.
            Captured scan photos may include your face, but live face-mesh coordinates are not
            sent to OpenAI. Per OpenAI&apos;s API data usage policy, data sent through the API is
            not stored or used for model training.
          </li>
        </ul>
        <p>No other third-party services receive your personal data.</p>
      </>
    ),
  },
  {
    num: "06",
    title: "Your rights (GDPR / CCPA)",
    body: (
      <>
        <p>You have the following rights regarding your personal data:</p>
        <ul>
          <li>
            <strong>Right of access</strong> — request a copy of the personal data we hold.
          </li>
          <li>
            <strong>Right to deletion</strong> — request that we delete your personal data.
          </li>
          <li>
            <strong>Right to portability</strong> — receive your data in a structured,
            machine-readable format.
          </li>
          <li>
            <strong>Right to rectification</strong> — request correction of inaccurate personal
            data.
          </li>
          <li>
            <strong>Right to restrict processing</strong> — limit how we process your data.
          </li>
          <li>
            <strong>Right to object</strong> — object to certain types of data processing.
          </li>
          <li>
            <strong>Right to opt out of sale</strong> — we do not sell personal data, but you may
            exercise this right at any time.
          </li>
        </ul>
        <p>
          To exercise any of these rights, contact{" "}
          <a href="mailto:drmustafa@bdqholdings.com">drmustafa@bdqholdings.com</a>. We will
          respond to all verified requests within 30 days.
        </p>
      </>
    ),
  },
  {
    num: "07",
    title: "Data retention",
    body: (
      <>
        <p>
          We retain your personal data for as long as your account remains active. You may delete
          your data at any time through <em>Profile › Delete account</em> in the app or by
          contacting <a href="mailto:drmustafa@bdqholdings.com">drmustafa@bdqholdings.com</a>.
        </p>
        <p>
          Upon receiving a deletion request, all associated personal data will be permanently
          removed from our systems within 30 days. Live face-alignment data is not retained
          beyond the active camera session. Captured scan photos that include your face are
          retained until you delete your account or request deletion.
        </p>
      </>
    ),
  },
  {
    num: "08",
    title: "Camera and photo permissions",
    body: (
      <>
        <p>
          Glowlytics requires camera access to capture skin scan photos. Here is how we handle
          photos that may include your face:
        </p>
        <ul>
          <li>Photos are stored locally on your device in a secure application directory.</li>
          <li>
            Photos are optionally sent to our backend for AI analysis, transmitted via encrypted
            connection.
          </li>
          <li>Photos are never shared with third parties for marketing or advertising purposes.</li>
          <li>
            You can revoke camera permissions at any time through your device settings.
          </li>
        </ul>
      </>
    ),
  },
  {
    num: "09",
    title: "Health data disclaimer",
    body: (
      <>
        <p>
          Glowlytics provides skin health insights for informational purposes only. Important
          limitations:
        </p>
        <ul>
          <li>
            Our analysis is <strong>non-diagnostic</strong> and does not constitute medical advice.
          </li>
          <li>
            Results should not be used as a substitute for professional medical consultation.
          </li>
          <li>Health data is never shared with insurance companies or employers.</li>
          <li>
            Always consult a qualified healthcare professional for medical concerns about your skin.
          </li>
        </ul>
      </>
    ),
  },
  {
    num: "10",
    title: "Children's privacy",
    body: (
      <>
        <p>
          Glowlytics is not intended for use by individuals under the age of 13. We do not
          knowingly collect personal information from children under 13.
        </p>
        <p>
          If you believe that a child under 13 has provided personal data to Glowlytics, please
          contact us immediately at{" "}
          <a href="mailto:drmustafa@bdqholdings.com">drmustafa@bdqholdings.com</a> and we will
          take steps to delete that information.
        </p>
      </>
    ),
  },
  {
    num: "11",
    title: "Changes to this policy",
    body: (
      <>
        <p>We may update this Privacy Policy from time to time. When we do:</p>
        <ul>
          <li>The updated policy will be posted in the app and on this page.</li>
          <li>The effective date at the top of this page will be updated.</li>
          <li>For material changes, we will provide prominent notice within the app.</li>
        </ul>
      </>
    ),
  },
  {
    num: "12",
    title: "Contact us",
    body: (
      <>
        <p>
          If you have any questions about this Privacy Policy or our data practices, please
          contact us:
        </p>
        <ul>
          <li>
            <strong>Company</strong> — BDQ Holdings LLC.
          </li>
          <li>
            <strong>Email</strong> —{" "}
            <a href="mailto:drmustafa@bdqholdings.com?subject=Glowlytics%20Privacy%20Inquiry">
              drmustafa@bdqholdings.com
            </a>
            .
          </li>
          <li>
            <strong>Subject line</strong> — Glowlytics Privacy Inquiry.
          </li>
          <li>
            <strong>Terms of Use</strong> — <Link href="/terms">glowlytics.ai/terms</Link>.
          </li>
          <li>
            <strong>Apple Standard EULA</strong> —{" "}
            <a
              href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/"
              target="_blank"
              rel="noopener"
            >
              apple.com/legal/internet-services/itunes/dev/stdeula
            </a>
            .
          </li>
        </ul>
      </>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <div className="legal-shell">
      <header className="legal-header">
        <div className="page-kicker">— Privacy</div>
        <h1>Your face stays on the phone.</h1>
        <p>
          Reading a face is intimate work. We treat it like a journal you&apos;ve left out on the
          table — closed.
        </p>
        <dl className="legal-meta">
          <div>
            <dt>Effective</dt>
            <dd>April 20, 2026</dd>
          </div>
          <div>
            <dt>Company</dt>
            <dd>BDQ Holdings LLC</dd>
          </div>
          <div>
            <dt>Contact</dt>
            <dd>
              <a href="mailto:drmustafa@bdqholdings.com">drmustafa@bdqholdings.com</a>
            </dd>
          </div>
        </dl>
      </header>

      <ol className="legal-sections">
        {sections.map((section) => (
          <li key={section.num} className="legal-section">
            <div className="legal-section-num">{section.num}</div>
            <div className="legal-section-body">
              <h2>{section.title}</h2>
              <div className="article-prose">{section.body}</div>
            </div>
          </li>
        ))}
      </ol>

      <style>{`
        .legal-shell {
          width: min(1080px, calc(100% - 48px));
          margin: 0 auto;
          padding: 88px 0 112px;
        }
        .legal-header {
          max-width: 720px;
          margin-bottom: 64px;
        }
        .legal-header h1 {
          margin: 14px 0 0;
          font-family: var(--font-display);
          font-style: italic;
          font-size: clamp(2.6rem, 5vw, 4.6rem);
          line-height: 1.02;
          letter-spacing: -0.02em;
          color: var(--ink);
          font-weight: 400;
          text-wrap: balance;
        }
        .legal-header p {
          margin: 22px 0 0;
          font-size: 1.05rem;
          line-height: 1.65;
          color: var(--muted);
          max-width: 560px;
          text-wrap: pretty;
        }
        .legal-meta {
          margin: 32px 0 0;
          padding: 22px 0 0;
          border-top: 1px solid var(--hairline);
          display: flex;
          flex-wrap: wrap;
          gap: 40px;
        }
        .legal-meta div {
          display: flex;
          flex-direction: column;
          gap: 4px;
        }
        .legal-meta dt {
          font-family: ui-monospace, "SF Mono", monospace;
          font-size: 10.5px;
          letter-spacing: 0.18em;
          text-transform: uppercase;
          color: var(--muted);
        }
        .legal-meta dd {
          margin: 0;
          font-size: 14px;
          color: var(--ink);
        }
        .legal-meta dd a {
          color: var(--accent);
          text-decoration: underline;
          text-underline-offset: 3px;
        }
        .legal-sections {
          list-style: none;
          padding: 0;
          margin: 0;
          counter-reset: legal-counter;
        }
        .legal-section {
          display: grid;
          grid-template-columns: 100px 1fr;
          gap: 40px;
          padding: 56px 0;
          border-top: 1px solid var(--hairline);
          align-items: start;
        }
        .legal-section:last-child {
          border-bottom: 1px solid var(--hairline);
        }
        .legal-section-num {
          font-family: var(--font-display);
          font-style: italic;
          font-size: 1.6rem;
          color: var(--accent);
          line-height: 1;
          padding-top: 6px;
        }
        .legal-section-body h2 {
          margin: 0 0 18px;
          font-family: var(--font-display);
          font-style: italic;
          font-size: clamp(1.7rem, 3vw, 2.3rem);
          line-height: 1.1;
          letter-spacing: -0.01em;
          color: var(--ink);
          font-weight: 400;
          text-wrap: balance;
        }
        .legal-section-body .article-prose {
          max-width: 720px;
        }
        @media (max-width: 720px) {
          .legal-shell {
            padding: 56px 0 80px;
          }
          .legal-header {
            margin-bottom: 40px;
          }
          .legal-meta {
            gap: 22px;
          }
          .legal-section {
            grid-template-columns: 1fr;
            gap: 12px;
            padding: 40px 0;
          }
          .legal-section-num {
            font-size: 1.2rem;
          }
        }
      `}</style>
    </div>
  );
}
