const TEST_GLOWLYTICS_CUTOVER_AT = '2026-07-20T00:00:00.000Z';

global.TEST_GLOWLYTICS_CUTOVER_AT = TEST_GLOWLYTICS_CUTOVER_AT;

process.env.GLOWLYTICS_CUTOVER_AT = TEST_GLOWLYTICS_CUTOVER_AT;

beforeEach(() => {
  process.env.GLOWLYTICS_CUTOVER_AT = TEST_GLOWLYTICS_CUTOVER_AT;
});
