// uv-report.js
// Branded PDF report generator for the "UV Mirror" marketing scan tool.
// buildReportPdf(scan, lead) -> Promise<Buffer> (a complete %PDF document).
// Pure pdfkit (bundled Helvetica fonts, headless-safe). No sharp, no fs, no network.
// Defensively reads possibly-missing fields; never throws on a partial/empty scan.

const PDFDocument = require('pdfkit');

// --- Brand palette (Dusk) -------------------------------------------------
const DUSK = '#5A3A5E'; // primary accent
const DUSK_LIGHT = '#8A6A8E';
const INK = '#2B2330';
const MUTED = '#7A7280';
const HAIRLINE = '#E4DCE6';
const PANEL = '#F3EEF4';

// --- Small, total helpers -------------------------------------------------
function num(v, def = 0) {
  const n = typeof v === 'number' ? v : Number(v);
  return Number.isFinite(n) ? n : def;
}
function clamp(n, lo, hi) {
  return n < lo ? lo : n > hi ? hi : n;
}
function str(v, def = '') {
  if (v == null) return def;
  return String(v);
}
function humanize(s) {
  return str(s)
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}
function fmtDate(v) {
  let d = v ? new Date(v) : new Date();
  if (isNaN(d.getTime())) d = new Date();
  return d.toISOString().slice(0, 10);
}

// intensity 0..1 -> [r,g,b] amber ramp (pale -> #F2B56A amber -> deep red).
function rampRGB(t) {
  t = clamp(num(t, 0), 0, 1);
  const stops = [
    { p: 0.0, c: [250, 245, 235] },
    { p: 0.5, c: [242, 181, 106] }, // #F2B56A
    { p: 1.0, c: [192, 57, 43] }, //  #C0392B
  ];
  let a = stops[0];
  let b = stops[stops.length - 1];
  for (let i = 0; i < stops.length - 1; i++) {
    if (t >= stops[i].p && t <= stops[i + 1].p) {
      a = stops[i];
      b = stops[i + 1];
      break;
    }
  }
  const span = b.p - a.p || 1;
  const f = (t - a.p) / span;
  return [
    Math.round(a.c[0] + (b.c[0] - a.c[0]) * f),
    Math.round(a.c[1] + (b.c[1] - a.c[1]) * f),
    Math.round(a.c[2] + (b.c[2] - a.c[2]) * f),
  ];
}

function severityColor(sev) {
  switch (str(sev).toLowerCase()) {
    case 'high':
      return '#C0392B';
    case 'moderate':
      return '#E08A2E';
    case 'low':
      return '#3E9D6B';
    default:
      return DUSK;
  }
}

function asymmetrySentence(a) {
  const dom = str(a.dominantSide, 'balanced').toLowerCase();
  const score = clamp(Math.round(num(a.score, 0)), 0, 100);
  if (dom === 'balanced' || (dom !== 'left' && dom !== 'right') || score < 8) {
    return (
      'Your left and right sides show a well-balanced distribution of sun ' +
      'exposure (asymmetry score ' + score + '/100).'
    );
  }
  const intensity = score >= 50 ? 'noticeably' : score >= 25 ? 'moderately' : 'slightly';
  const other = dom === 'left' ? 'right' : 'left';
  return (
    'Your ' + dom + ' side shows ' + intensity + ' more accumulated sun damage ' +
    'than your ' + other + ' side (asymmetry score ' + score + '/100). ' +
    'Sides are described from your own perspective.'
  );
}

const DISCLAIMER =
  'This report is a cosmetic and wellness estimate generated by automated image ' +
  'analysis for informational and marketing purposes only. It is NOT a medical ' +
  'device, diagnosis, or treatment recommendation, and it does not detect, screen ' +
  'for, or rule out skin cancer or any other medical condition. Results depend on ' +
  'lighting, camera, and pose, and may be inaccurate. If you notice a new, changing, ' +
  'or concerning spot on your skin, consult a licensed dermatologist.';

const METHODOLOGY =
  'We estimate cumulative UV / sun damage from a single photo using deterministic ' +
  'computer vision. Each pixel is converted to the CIELAB color space and scored for ' +
  'pigmentation depth (Individual Typology Angle), localized spot contrast, and ' +
  'luminance darkening. Per-pixel scores are aggregated into facial regions and a ' +
  'left/right asymmetry comparison. No AI model "decides" your result — the same photo ' +
  'always yields the same numbers.';

/**
 * Build the branded UV Mirror PDF report.
 *
 * @param {object} scan  Analysis result. All fields optional / guarded:
 *   scan.overall   {{ sunDamageScore:number(0-100), severity:string, confidence:number(0..1) }}
 *   scan.regions   {Array<{ id, label, side, score(0-100), intensity(0..1), spotCount }>}
 *   scan.asymmetry {{ score(0-100), dominantSide:'left'|'right'|'balanced', leftMean, rightMean }}
 *   scan.heatmap   {{ cols:number, rows:number, cells:number[] (row-major, each 0..1) }}
 *   scan.created_at (optional date/ISO string)
 * @param {object} lead  {{ email?:string }} — personalization (optional).
 * @returns {Promise<Buffer>} a complete PDF document.
 */
async function buildReportPdf(scan, lead) {
  return new Promise((resolve, reject) => {
    try {
      scan = scan && typeof scan === 'object' ? scan : {};
      lead = lead && typeof lead === 'object' ? lead : {};
      const overall = scan.overall && typeof scan.overall === 'object' ? scan.overall : {};
      const regions = Array.isArray(scan.regions) ? scan.regions : [];
      const asymmetry = scan.asymmetry && typeof scan.asymmetry === 'object' ? scan.asymmetry : {};
      const heatmap = scan.heatmap && typeof scan.heatmap === 'object' ? scan.heatmap : {};

      const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const left = doc.page.margins.left;
      const right = doc.page.width - doc.page.margins.right;
      const bottom = doc.page.height - doc.page.margins.bottom;
      const contentWidth = right - left;

      function ensureSpace(h) {
        if (doc.y + h > bottom) doc.addPage();
      }
      function sectionTitle(title) {
        ensureSpace(46);
        doc.moveDown(0.6);
        doc.fillColor(DUSK).font('Helvetica-Bold').fontSize(13).text(title, left, doc.y);
        const ty = doc.y + 2;
        doc.moveTo(left, ty).lineTo(right, ty).lineWidth(0.75).strokeColor(HAIRLINE).stroke();
        doc.y = ty + 6;
      }
      function body(text, opts) {
        doc.fillColor(INK).font('Helvetica').fontSize(10).text(text, left, doc.y, Object.assign({ width: contentWidth }, opts || {}));
      }

      // ---------------------------------------------------------------- Header
      doc.fillColor(DUSK).font('Helvetica-Bold').fontSize(23);
      doc.text('Glowlytics', left, doc.y, { continued: true });
      doc.fillColor(DUSK_LIGHT).text('  \u2014 UV Mirror Report');
      doc.fillColor(MUTED).font('Helvetica').fontSize(10);
      doc.text('Your personalized UV / sun-damage & facial-asymmetry estimate', left, doc.y + 2, {
        width: contentWidth,
      });
      doc.fontSize(8.5).fillColor(MUTED);
      if (lead.email) {
        doc.text('Prepared for ' + str(lead.email) + '  \u00b7  Generated ' + fmtDate(scan.created_at), left, doc.y + 2);
      } else {
        doc.text('Generated ' + fmtDate(scan.created_at), left, doc.y + 2);
      }
      doc.moveTo(left, doc.y + 4).lineTo(right, doc.y + 4).lineWidth(1).strokeColor(DUSK).stroke();
      doc.y += 12;

      // -------------------------------------------------- Overall score gauge
      sectionTitle('Overall sun-damage estimate');
      const score = clamp(Math.round(num(overall.sunDamageScore, 0)), 0, 100);
      const severity = str(overall.severity, 'unknown');
      const confidence = clamp(num(overall.confidence, 0), 0, 1);

      const blockY = doc.y;
      // Big score numeral
      doc.fillColor(severityColor(severity)).font('Helvetica-Bold').fontSize(40).text(String(score), left, blockY, { width: 90 });
      doc.fillColor(MUTED).font('Helvetica').fontSize(9).text('/ 100', left, blockY + 40, { width: 90 });

      const gx = left + 110;
      const gw = right - gx;
      // Severity pill + confidence
      doc.font('Helvetica-Bold').fontSize(12).fillColor(severityColor(severity)).text(humanize(severity) + ' severity', gx, blockY + 2, { width: gw });
      doc.font('Helvetica').fontSize(9).fillColor(MUTED).text('Estimate confidence: ' + Math.round(confidence * 100) + '%', gx, doc.y + 1, { width: gw });

      // Gauge bar
      const barY = blockY + 40;
      const barH = 16;
      doc.roundedRect(gx, barY, gw, barH, 4).fill(PANEL);
      const fillW = clamp(Math.round(gw * (score / 100)), 2, gw);
      doc.roundedRect(gx, barY, fillW, barH, 4).fill(severityColor(severity));
      // band tick labels
      doc.font('Helvetica').fontSize(7).fillColor(MUTED);
      doc.text('0  \u00b7  low', gx, barY + barH + 3, { width: gw / 3, align: 'left' });
      doc.text('moderate', gx + gw / 3, barY + barH + 3, { width: gw / 3, align: 'center' });
      doc.text('high  \u00b7  100', gx, barY + barH + 3, { width: gw, align: 'right' });
      doc.y = barY + barH + 18;

      // ---------------------------------------------------------- Region table
      sectionTitle('Region breakdown');
      if (regions.length === 0) {
        doc.fillColor(MUTED).font('Helvetica-Oblique').fontSize(10).text('No regional data was available for this scan.', left, doc.y, { width: contentWidth });
        doc.font('Helvetica');
        doc.y += 6;
      } else {
        const colSwatch = left;
        const colLabel = left + 22;
        const colScore = right - 150;
        const colSpots = right - 70;
        // header
        const hY = doc.y;
        doc.fillColor(DUSK).font('Helvetica-Bold').fontSize(9);
        doc.text('REGION', colLabel, hY, { width: colScore - colLabel - 6 });
        doc.text('SCORE', colScore, hY, { width: 70, align: 'left' });
        doc.text('SPOTS', colSpots, hY, { width: 70, align: 'left' });
        doc.y = hY + 13;
        doc.moveTo(left, doc.y - 2).lineTo(right, doc.y - 2).lineWidth(0.5).strokeColor(HAIRLINE).stroke();

        for (const r of regions) {
          const reg = r && typeof r === 'object' ? r : {};
          ensureSpace(18);
          const rowY = doc.y + 2;
          const label = str(reg.label, '') || humanize(reg.id) || 'Region';
          const rScore = clamp(Math.round(num(reg.score, 0)), 0, 100);
          const rSpots = Math.max(0, Math.round(num(reg.spotCount, 0)));
          const rIntensity = clamp(num(reg.intensity, rScore / 100), 0, 1);
          const side = str(reg.side, '');
          // intensity swatch
          doc.rect(colSwatch, rowY + 1, 12, 9).fill(rampRGB(rIntensity));
          doc.rect(colSwatch, rowY + 1, 12, 9).lineWidth(0.4).strokeColor(HAIRLINE).stroke();
          const labelTxt = side && side !== 'center' ? label + ' (' + side + ')' : label;
          doc.fillColor(INK).font('Helvetica').fontSize(9.5).text(labelTxt, colLabel, rowY, { width: colScore - colLabel - 6 });
          doc.fillColor(INK).text(String(rScore), colScore, rowY, { width: 70 });
          doc.fillColor(INK).text(String(rSpots), colSpots, rowY, { width: 70 });
          doc.y = rowY + 13;
          doc.moveTo(left, doc.y - 2).lineTo(right, doc.y - 2).lineWidth(0.25).strokeColor(HAIRLINE).stroke();
        }
        doc.y += 4;
      }

      // ------------------------------------------------------ Asymmetry summary
      sectionTitle('Left / right asymmetry');
      body(asymmetrySentence(asymmetry));
      const lMean = clamp(num(asymmetry.leftMean, NaN), 0, 1);
      const rMean = clamp(num(asymmetry.rightMean, NaN), 0, 1);
      if (Number.isFinite(num(asymmetry.leftMean, NaN)) && Number.isFinite(num(asymmetry.rightMean, NaN))) {
        doc.fillColor(MUTED).font('Helvetica').fontSize(9).text(
          'Mean intensity \u2014 left: ' + lMean.toFixed(2) + '   right: ' + rMean.toFixed(2),
          left,
          doc.y + 2,
          { width: contentWidth }
        );
      }
      doc.y += 6;

      // ------------------------------------------------------------- Heatmap
      sectionTitle('Damage heatmap');
      const cols = Math.max(0, Math.round(num(heatmap.cols, 0)));
      const rows = Math.max(0, Math.round(num(heatmap.rows, 0)));
      const cells = Array.isArray(heatmap.cells) ? heatmap.cells : [];
      if (cols > 0 && rows > 0 && cells.length > 0) {
        const boxW = Math.min(230, contentWidth);
        const cw = boxW / cols;
        const ch = cw; // approx square cells
        const boxH = ch * rows;
        ensureSpace(boxH + 28);
        const ox = left;
        const oy = doc.y;
        for (let r = 0; r < rows; r++) {
          for (let c = 0; c < cols; c++) {
            const idx = r * cols + c;
            const v = idx < cells.length ? num(cells[idx], 0) : 0;
            // +0.4 overlap avoids hairline gaps between cells
            doc.rect(ox + c * cw, oy + r * ch, cw + 0.4, ch + 0.4).fill(rampRGB(v));
          }
        }
        doc.rect(ox, oy, cw * cols, ch * rows).lineWidth(0.5).strokeColor(HAIRLINE).stroke();

        // gradient legend
        const legX = ox + boxW + 24;
        const legW = Math.min(140, right - legX);
        if (legW > 40) {
          const legY = oy + 4;
          const steps = 28;
          const sw = legW / steps;
          for (let i = 0; i < steps; i++) {
            doc.rect(legX + i * sw, legY, sw + 0.4, 10).fill(rampRGB(i / (steps - 1)));
          }
          doc.fillColor(MUTED).font('Helvetica').fontSize(7.5);
          doc.text('less', legX, legY + 13, { width: legW / 2, align: 'left' });
          doc.text('more damage', legX, legY + 13, { width: legW, align: 'right' });
          doc.fillColor(MUTED).fontSize(8).text('Warmer cells indicate higher estimated UV / sun damage in that area of the face.', legX, legY + 26, { width: Math.max(60, right - legX) });
        }
        doc.y = oy + boxH + 10;
      } else {
        doc.fillColor(MUTED).font('Helvetica-Oblique').fontSize(10).text('No heatmap data was available for this scan.', left, doc.y, { width: contentWidth });
        doc.font('Helvetica');
        doc.y += 6;
      }

      // ----------------------------------------------------------- Methodology
      sectionTitle('How this was measured');
      body(METHODOLOGY);

      // ------------------------------------------------------------ Disclaimer
      sectionTitle('Important — please read');
      doc.fillColor(MUTED).font('Helvetica-Oblique').fontSize(8.5).text(DISCLAIMER, left, doc.y, { width: contentWidth });
      doc.font('Helvetica');
      doc.y += 8;

      // -------------------------------------------------------------- CTA box
      ensureSpace(74);
      const ctaY = doc.y + 4;
      const ctaH = 60;
      doc.roundedRect(left, ctaY, contentWidth, ctaH, 8).fill(DUSK);
      doc.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(13).text('Track your skin over time with Glowlytics', left + 16, ctaY + 12, { width: contentWidth - 32 });
      doc.fillColor('#EBDDEE').font('Helvetica').fontSize(9.5).text(
        'Download the Glowlytics app to re-scan, monitor changes month over month, and get a personalized SPF & skincare routine.',
        left + 16,
        doc.y + 2,
        { width: contentWidth - 32 }
      );
      doc.y = ctaY + ctaH + 10;

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { buildReportPdf };
