import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Glowlytics Privacy Policy. Learn how BDQ Holdings LLC handles your data.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen" style={{ background: "#EDF5F6", color: "#1a2b3c" }}>
      {/* Page Header */}
      <div
        style={{
          maxWidth: 800,
          margin: "0 auto",
          padding: "80px 24px 0",
          textAlign: "center",
        }}
      >
        <h1
          style={{
            fontSize: 42,
            fontWeight: 700,
            lineHeight: 1.15,
            letterSpacing: "-1.5px",
            color: "#0e1e2e",
            marginBottom: 16,
          }}
        >
          Privacy Policy
        </h1>
        <p style={{ fontSize: 15, color: "#7a8f9e", lineHeight: 1.6 }}>
          <strong style={{ color: "#5a6f7e", fontWeight: 600 }}>Effective Date:</strong> March 10, 2026
          <br />
          <strong style={{ color: "#5a6f7e", fontWeight: 600 }}>Company:</strong> BDQ Holdings LLC
          <br />
          <strong style={{ color: "#5a6f7e", fontWeight: 600 }}>Contact:</strong>{" "}
          <a
            href="mailto:drmustafa@bdqholdings.com"
            style={{ color: "#39B5BF", textDecoration: "none", fontWeight: 500 }}
          >
            drmustafa@bdqholdings.com
          </a>
        </p>
      </div>

      {/* Content */}
      <div
        style={{
          maxWidth: 800,
          margin: "40px auto 80px",
          padding: "0 24px",
          display: "flex",
          flexDirection: "column",
          gap: 20,
        }}
      >
        {/* 1. Information We Collect */}
        <div style={cardStyle}>
          <h2 style={h2Style}>
            <span style={numStyle}>1</span> Information We Collect
          </h2>
          <p style={pStyle}>
            We collect the following types of information to provide and improve the Glowlytics
            experience:
          </p>
          <ul style={ulStyle}>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Account information</strong> — name, email address, and authentication
              credentials managed through Clerk
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Skin scan photos</strong> — images captured via your device camera for skin
              analysis
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Health metrics</strong> — skin scores, condition assessments, and trend data
              generated by our AI analysis
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Product usage data</strong> — skincare products you log, including barcode
              scans and usage patterns
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Demographic information</strong> — age, skin type, and related details you
              provide during onboarding
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Device information</strong> — device type, operating system, and app version
              for compatibility and troubleshooting
            </li>
          </ul>
        </div>

        {/* 2. How We Use Your Data */}
        <div style={cardStyle}>
          <h2 style={h2Style}>
            <span style={numStyle}>2</span> How We Use Your Data
          </h2>
          <p style={pStyle}>
            Your data is used exclusively to deliver and improve the Glowlytics service:
          </p>
          <ul style={ulStyle}>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Skin analysis</strong> — processing your scan photos through our fine-tuned
              AI model to identify conditions and generate scores
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Trend tracking</strong> — monitoring changes in your skin health over time to
              surface meaningful insights
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Personalized recommendations</strong> — providing evidence-based guidance
              informed by AAD and ACOG clinical guidelines via our RAG pipeline
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Service improvement</strong> — understanding aggregate usage patterns to
              improve app functionality and accuracy
            </li>
          </ul>
          <p style={{ ...pStyle, marginBottom: 0 }}>
            <strong>We do not sell your data. We do not use your data for advertising.</strong>
          </p>
        </div>

        {/* 3. Data Storage and Security */}
        <div style={cardStyle}>
          <h2 style={h2Style}>
            <span style={numStyle}>3</span> Data Storage and Security
          </h2>
          <p style={pStyle}>
            Your data is stored using a combination of local and server-side storage:
          </p>
          <ul style={ulStyle}>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Local device storage</strong> — scan history, preferences, and cached data
              are stored on your device using AsyncStorage
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Encrypted backend</strong> — data synced to our servers is stored in
              PostgreSQL with TLS encryption in transit
            </li>
          </ul>
          <p style={{ ...pStyle, marginBottom: 0 }}>
            We employ industry-standard security practices to protect your information, including
            encrypted connections, secure authentication via Clerk, and server-side API key
            management to prevent exposure of credentials.
          </p>
        </div>

        {/* 4. Third-Party Services */}
        <div style={cardStyle}>
          <h2 style={h2Style}>
            <span style={numStyle}>4</span> Third-Party Services
          </h2>
          <p style={pStyle}>Glowlytics integrates the following third-party services:</p>
          <ul style={ulStyle}>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Clerk</strong> — handles authentication, account management, and secure
              session tokens. Subject to{" "}
              <a
                href="https://clerk.com/privacy"
                target="_blank"
                rel="noopener"
                style={linkStyle}
              >
                Clerk&apos;s Privacy Policy
              </a>
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>OpenAI</strong> — powers our vision-based skin analysis via their API. Per
              OpenAI&apos;s API data usage policy, data sent through the API is not stored or used
              for model training
            </li>
          </ul>
          <p style={{ ...pStyle, marginBottom: 0 }}>
            No other third-party services receive your personal data.
          </p>
        </div>

        {/* 5. Your Rights */}
        <div style={cardStyle}>
          <h2 style={h2Style}>
            <span style={numStyle}>5</span> Your Rights (GDPR / CCPA)
          </h2>
          <p style={pStyle}>
            You have the following rights regarding your personal data:
          </p>
          <ul style={ulStyle}>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Right of access</strong> — request a copy of the personal data we hold about
              you
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Right to deletion</strong> — request that we delete your personal data
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Right to portability</strong> — receive your data in a structured,
              machine-readable format
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Right to rectification</strong> — request correction of inaccurate personal
              data
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Right to restrict processing</strong> — limit how we process your data
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Right to object</strong> — object to certain types of data processing
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Right to opt out of sale</strong> — we do not sell personal data, but you
              may exercise this right at any time
            </li>
          </ul>
          <p style={{ ...pStyle, marginBottom: 0 }}>
            To exercise any of these rights, contact{" "}
            <a href="mailto:drmustafa@bdqholdings.com" style={linkStyle}>
              drmustafa@bdqholdings.com
            </a>
            . We will respond to all verified requests within 30 days.
          </p>
        </div>

        {/* 6. Data Retention */}
        <div style={cardStyle}>
          <h2 style={h2Style}>
            <span style={numStyle}>6</span> Data Retention
          </h2>
          <p style={pStyle}>
            We retain your personal data for as long as your account remains active. You may delete
            your data at any time through the app&apos;s settings or by contacting us at{" "}
            <a href="mailto:drmustafa@bdqholdings.com" style={linkStyle}>
              drmustafa@bdqholdings.com
            </a>
            .
          </p>
          <p style={{ ...pStyle, marginBottom: 0 }}>
            Upon receiving a deletion request, all associated personal data will be permanently
            removed from our systems within 30 days.
          </p>
        </div>

        {/* 7. Camera and Photo Permissions */}
        <div style={cardStyle}>
          <h2 style={h2Style}>
            <span style={numStyle}>7</span> Camera and Photo Permissions
          </h2>
          <p style={pStyle}>
            Glowlytics requires camera access to capture skin scan photos. Here is how we handle
            your photos:
          </p>
          <ul style={ulStyle}>
            <li style={liStyle}>
              <span style={bulletStyle} />
              Photos are stored locally on your device in a secure application directory
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              Photos are optionally sent to our backend for AI analysis, transmitted via encrypted
              connection
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              Photos are never shared with third parties for marketing or advertising purposes
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              You can revoke camera permissions at any time through your device settings
            </li>
          </ul>
        </div>

        {/* 8. Health Data Disclaimer */}
        <div style={cardStyle}>
          <h2 style={h2Style}>
            <span style={numStyle}>8</span> Health Data Disclaimer
          </h2>
          <p style={pStyle}>
            Glowlytics provides skin health insights for informational purposes only. Important
            limitations:
          </p>
          <ul style={ulStyle}>
            <li style={liStyle}>
              <span style={bulletStyle} />
              Our analysis is <strong>non-diagnostic</strong> and does not constitute medical
              advice
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              Results should not be used as a substitute for professional medical consultation
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              Health data is never shared with insurance companies or employers
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              Always consult a qualified healthcare professional for medical concerns about your
              skin
            </li>
          </ul>
        </div>

        {/* 9. Children's Privacy */}
        <div style={cardStyle}>
          <h2 style={h2Style}>
            <span style={numStyle}>9</span> Children&apos;s Privacy
          </h2>
          <p style={pStyle}>
            Glowlytics is not intended for use by individuals under the age of 13. We do not
            knowingly collect personal information from children under 13.
          </p>
          <p style={{ ...pStyle, marginBottom: 0 }}>
            If you believe that a child under 13 has provided personal data to Glowlytics, please
            contact us immediately at{" "}
            <a href="mailto:drmustafa@bdqholdings.com" style={linkStyle}>
              drmustafa@bdqholdings.com
            </a>{" "}
            and we will take steps to delete that information.
          </p>
        </div>

        {/* 10. Changes to This Policy */}
        <div style={cardStyle}>
          <h2 style={h2Style}>
            <span style={numStyle}>10</span> Changes to This Policy
          </h2>
          <p style={pStyle}>We may update this Privacy Policy from time to time. When we do:</p>
          <ul style={ulStyle}>
            <li style={liStyle}>
              <span style={bulletStyle} />
              The updated policy will be posted in the app and on this page
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              The effective date at the top of this page will be updated
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              For material changes, we will provide prominent notice within the app
            </li>
          </ul>
        </div>

        {/* 11. Contact */}
        <div style={cardStyle}>
          <h2 style={h2Style}>
            <span style={numStyle}>11</span> Contact Us
          </h2>
          <p style={pStyle}>
            If you have any questions about this Privacy Policy or our data practices, please
            contact us:
          </p>
          <ul style={ulStyle}>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Company:</strong> BDQ Holdings LLC
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Email:</strong>{" "}
              <a
                href="mailto:drmustafa@bdqholdings.com?subject=Glowlytics%20Privacy%20Inquiry"
                style={linkStyle}
              >
                drmustafa@bdqholdings.com
              </a>
            </li>
            <li style={liStyle}>
              <span style={bulletStyle} />
              <strong>Subject line:</strong> Glowlytics Privacy Inquiry
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}

/* ── Shared inline styles ── */

const cardStyle: React.CSSProperties = {
  background: "#fff",
  borderRadius: 20,
  padding: "36px 40px",
  boxShadow: "0 2px 12px rgba(0,0,0,0.04)",
  border: "1px solid rgba(0,0,0,0.04)",
};

const h2Style: React.CSSProperties = {
  fontSize: 20,
  fontWeight: 700,
  color: "#0e1e2e",
  marginBottom: 16,
  display: "flex",
  alignItems: "center",
  gap: 12,
};

const numStyle: React.CSSProperties = {
  width: 30,
  height: 30,
  borderRadius: 10,
  background: "#EDF5F6",
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  fontSize: 13,
  fontWeight: 700,
  color: "#39B5BF",
  flexShrink: 0,
};

const pStyle: React.CSSProperties = {
  fontSize: 15,
  color: "#4a5e6d",
  lineHeight: 1.75,
  marginBottom: 12,
};

const ulStyle: React.CSSProperties = {
  listStyle: "none",
  padding: 0,
  margin: "0 0 12px 0",
};

const liStyle: React.CSSProperties = {
  fontSize: 15,
  color: "#4a5e6d",
  lineHeight: 1.75,
  paddingLeft: 20,
  position: "relative",
  display: "flex",
  alignItems: "flex-start",
  gap: 0,
};

const bulletStyle: React.CSSProperties = {
  position: "absolute",
  left: 0,
  top: 11,
  width: 6,
  height: 6,
  borderRadius: "50%",
  background: "#39B5BF",
  flexShrink: 0,
};

const linkStyle: React.CSSProperties = {
  color: "#39B5BF",
  textDecoration: "none",
  fontWeight: 500,
};
